#!/usr/bin/env bash

fatal() {
  echo "FATAL ERROR: $@"
  exit 1
}
trap 'sudo -k' EXIT

case $1 in 

status)
  STATUS=$(nmcli con show Hotspot | rg GENERAL.STATE --include-zero --count)

  echo $STATUS
 ;;

up)
  zenity --password | sudo -S nmcli con up Hotspot
  ;;

down)
  zenity --password | sudo -S nmcli con down Hotspot
  ;;
esac

exit 0
