#!/usr/bin/env bash

fatal() {
  echo "FATAL ERROR: $@"
  exit 1
}
trap 'sudo -k' EXIT

case $1 in 

status)
  STATUS=$(nmcli con show proton-us-udp | rg GENERAL.STATE --include-zero --count)

  echo $STATUS
 ;;

up)
  nmcli con up proton-us-udp
  ;;

down)
  nmcli con down proton-us-udp 
  ;;
esac

exit 0
